@baseUrl={{$dotenv DEV_URL}}
@tenant={{$dotenv TENANT}}
@username={{$dotenv USER}}
@password={{$dotenv PASSWORD}}
@requestor=pgsRest
@correlation=20240122000000
@costCenter=2014615
@imageColor=true
@amountPayment=1000
@amountToken=400
@amountRefund=70







### Create ShoppingCart
# @name shopCart

PUT {{baseUrl}}/paymentcart/{{tenant}} HTTP/1.1
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "requestor": "{{requestor}}",
  "correlationId": "{{correlation}}",
  "amount": "{{amountPayment}}",
  "currency": "EUR",
  "reason": "Daily parking.",
  "reference": "myshop-cart-id",
  "successCallbackUrl": "http://localhost:3001/success",
  "failureCallbackUrl": "http://localhost:3001/failure",
  "customStyle": "input[type=\"submit\"] {\n    background-color: blue;\n}",
  "tokenRequired": true
}

@cartId = {{shopCart.response.body.$.cartId}}
@pgsToken = {{shopCart.response.body.$.pgsToken}}



### Get ShoppingCart Status
GET {{baseUrl}}/status/{{tenant}}/{{cartId}}/{{correlation}}/{{requestor}} HTTP/1.1
Authorization: Basic {{username}} {{password}}
Accept: application/json



### Get Payment types
GET {{baseUrl}}/paymenttypes/{{tenant}}/{{cartId}}/{{correlation}}/{{requestor}}/en-Gb
    ?costCenter={{costCenter}}
    &imageColor={{imageColor}}
Authorization: Basic {{username}} {{password}}
Accept: application/json



### Refund Full
PUT {{baseUrl}}/refund/full/{{tenant}}/{{cartId}}/Double%20booking HTTP/1.1
Authorization: Basic {{username}} {{password}}
Accept: application/json



### Refund Partial
PUT {{baseUrl}}/refund/partial/{{tenant}}/{{cartId}}/Discount%20for%20customer/{{amountRefund}} HTTP/1.1
Authorization: Basic {{username}} {{password}}
Accept: application/json











### Token validation
PUT {{baseUrl}}/tokenvalidity/{{tenant}} HTTP/1.1
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "requestor": "{{requestor}}",
  "correlationId": "{{correlation}}",
  "pgsToken": "{{pgsToken}}",
  "validatePsp": true
}



### Token deletion
DELETE {{baseUrl}}/tokendelete/{{tenant}} HTTP/1.1
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "requestor": "{{requestor}}",
  "correlationId": "{{correlation}}",
  "pgsToken": "{{pgsToken}}"
}
















### Create TokenCart
# @name tokenCart

PUT {{baseUrl}}/tokencart/{{tenant}} HTTP/1.1
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "requestor": "{{requestor}}",
  "correlationId": "{{correlation}}",
  "amount": "{{amountToken}}",
  "currency": "EUR",
  "reason": "Monthly parking.",
  "reference": "myshop-cart-id"
}

@tokencartId = {{tokenCart.response.body.$.cartId}}



### Get Tokencart Status
GET {{baseUrl}}/status/{{tenant}}/{{tokencartId}}/{{correlation}}/{{requestor}} HTTP/1.1
Authorization: Basic {{username}} {{password}}
Accept: application/json



### Payment TokenCart with token
PUT {{baseUrl}}/paymentwithtoken/{{tenant}} HTTP/1.1
Authorization: Basic {{username}} {{password}}
Content-Type: application/json
Accept: application/json

{
  "requestor": "{{requestor}}",
  "correlationId": "{{correlation}}",
  "cartId": "{{tokencartId}}",
  "pgsToken": "{{pgsToken}}",
  "transactionInitiator": "CUSTOMER"
}



### Refund Full
PUT {{baseUrl}}/refund/full/{{tenant}}/{{tokencartId}}/FullRefund HTTP/1.1
Authorization: Basic {{username}} {{password}}
Accept: application/json



### Refund Partial
PUT {{baseUrl}}/refund/partial/{{tenant}}/{{tokencartId}}/PartialRefund/{{amountRefund}} HTTP/1.1
Authorization: Basic {{username}} {{password}}
Accept: application/json



